name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
            - run: npm install -g bats
            - run: bats --version

    get-pr:
        runs-on: ubuntu-latest
        steps:
        - name : Get the pull request number
          id: pr_number
          run: echo "PR number is www.pr-${{ github.event.number }}"
