name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
    pull_request:
        types: [opened, reopened]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
            - run: npm install -g bats
            - run: bats --version
    dump-github:
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
    get-pr:
        runs-on: ubuntu-latest
        steps:
        - name : Get the pull request number
          id: pr_number
          run: echo "PR number is https://www.github.com/${{github.repository}}/${{ github.event.number }}"
