name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
    pull_request:
        types: [opened, reopened]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
            - run: npm install -g bats
            - run: bats --version
    dump-github:
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
    get-pr:
        runs-on: ubuntu-latest
        steps:
            - name: save PR
              env:
                PR_LINK: "https://www.github.com/${{github.repository}}/pull/${{ github.event.number }}"
              run: echo "pr_link=$PR_LINK >> $GITHUB_ENV"
    comment-pr:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        needs: [get-pr]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Comment PR
              uses: thollander/actions-comment-pull-request@v2.4.3
              with:
                message: |
                    Hello @${{ github.actor }}! Thanks for opening this PR.
                    You can see the PR [here](${{ env.pr_link }}).
